### ISSUE TITLE
'[BUG]' Unable to apply stat points to anything besides Health, Magicka, or Stamina.

### ISSUE THREAD

**Issue by grimcreapere** [Styyx1/Ruvaak-Readme#16] opened 2022-08-27 05:13 UTC
**Required: Modlist.txt**
[modlist.txt](https://github.com/chri3i/Ruvaak-Readme/files/9437342/modlist.txt)
You must also include your modlist.txt from `Ruvaak\profiles\Ruvaak`

**Describe the bug**
Skills can not be leveled up.
edit correction: health/magicka/stamina do not apply either.
**To Reproduce**

1. Level up
2. go to skills/stats menu
3. apply points to any skills ex Smithing or Two-Handed
4. choose Health, Magicka, or stamina to finish
5. Menu closes but no points were added to the appropriate skills. They always revert to their previous number: ex Smithing, starts at 10, put 5 points into it and it shows 15, menu closes but the skill is still at 10 in the menu and is also still 10 on next level up dialog.

**Expected behavior**
 Expect skills to actually level up. They dont.

**Did you add any additional mods?**
No changes to mod list. Fresh install
***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by grimcreapere** [comment] 2022-08-27 17:04
After some searching, it appears to be the Experience mod.

Quoted from the mod maker on Nexus: Firstly, if skill leveling doesn't seem to be working, there's a quick fix. Check your current level. Let's say you're level 5, for this example. You want to add 1 to your current level and then subtract it. To do that, you would then open the console and type player.setlevel 6, enter that, close the console and make a save, and then open the console again and type player.setlevel 5 to return your character to the correct level. Save the game again, and you should be set to go. Strictly speaking, the saving isn't necessary, but in my experience it makes the fix more reliable. This should only need to be done once per character, unless you reinstall the mod.

This fix worked to a degree. The skills i had attempted to upgrade prior to doing this fix were not able to be improved with points at all, but new skills worked fine. Started a new character after doing the fix (did not reload the game, just made a save and started new guy) and everything appears to be working fine now.

**Comment by chri3i** [comment] 2022-08-27 17:06
it will be fixed in the upcoming update, the issue is with standing stones that modify EXP gain

**Comment by grimcreapere** [comment] 2022-08-27 19:12
Awesome! You put together a great pack, im really enjoying so far, thank you :)

**Comment by Styyx1** [comment] 2023-07-16 13:30
completely reworked leveling since then. I forgot to close this issue

**Closed by Styyx1** 2023-07-16 13:30 UTC
Labels: bug
